# Google Cloud Build configuration for ETrade Strategy
# This file builds and deploys the trading bot to Google Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/etrade-strategy:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/etrade-strategy:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'etrade-strategy'
      - '--image'
      - 'gcr.io/$PROJECT_ID/etrade-strategy:$COMMIT_SHA'
      - '--region'
      - 'us-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '1'
      - '--max-instances'
      - '1'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'STRATEGY_MODE=standard,AUTOMATION_MODE=demo,ENVIRONMENT=production'
      - '--port'
      - '8080'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/etrade-strategy:$COMMIT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100